version: "3.4"

services:
  symfony-web-application:
    build:
      context: .
      target: symfony-web-application
    volumes:
      - .:/app
    stop_grace_period: 0s
  
  nginx:
    build:
      context: .
      target: nginx
    volumes:
      - .:/app
    stop_grace_period: 0s
    ports:
      - 8000:80

  php_fpm:
    build:
      context: .
      target: php_fpm
    volumes:
      - .:/app
    stop_grace_period: 0s
